import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy | LinkedInbox",
  description: "Privacy Policy for LinkedInbox - LinkedIn outreach analytics platform",
};

export default function PrivacyPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0a] text-white">
      <div className="max-w-4xl mx-auto px-6 py-16">
        <h1 className="text-4xl font-bold mb-8">Privacy Policy</h1>
        <p className="text-zinc-400 mb-12">Last updated: January 2026</p>

        <div className="prose prose-invert prose-zinc max-w-none">
          <section className="mb-12">
            <p className="text-zinc-300 leading-relaxed">
              This Privacy Policy describes Our policies and procedures on the collection, use and disclosure 
              of Your information when You use the Service and tells You about Your privacy rights and how the 
              law protects You.
            </p>
            <p className="text-zinc-300 leading-relaxed mt-4">
              We use Your Personal data to provide and improve the Service. By using the Service, You agree to 
              the collection and use of information in accordance with this Privacy Policy.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Interpretation and Definitions</h2>
            
            <h3 className="text-xl font-medium text-white mt-6 mb-3">Interpretation</h3>
            <p className="text-zinc-300 leading-relaxed">
              The words of which the initial letter is capitalized have meanings defined under the following 
              conditions. The following definitions shall have the same meaning regardless of whether they 
              appear in singular or in plural.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">Definitions</h3>
            <p className="text-zinc-300 mb-2">For the purposes of this Privacy Policy:</p>
            <ul className="list-disc list-inside text-zinc-300 space-y-2">
              <li><strong>Account</strong> means a unique account created for You to access our Service or parts of our Service.</li>
              <li><strong>Affiliate</strong> means an entity that controls, is controlled by or is under common control with a party, where "control" means ownership of 50% or more of the shares, equity interest or other securities entitled to vote for election of directors or other managing authority.</li>
              <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to LinkedInbox, Geneva, Switzerland.</li>
              <li><strong>Cookies</strong> are small files that are placed on Your computer, mobile device or any other device by a website, containing the details of Your browsing history on that website among its many uses.</li>
              <li><strong>Country</strong> refers to: Switzerland</li>
              <li><strong>Device</strong> means any device that can access the Service such as a computer, a cellphone or a digital tablet.</li>
              <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable individual.</li>
              <li><strong>Service</strong> refers to the Website.</li>
              <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of the Company.</li>
              <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the Service or from the Service infrastructure itself.</li>
              <li><strong>Website</strong> refers to LinkedInbox: www.linkedinbox.co</li>
              <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Collecting and Using Your Personal Data</h2>
            
            <h3 className="text-xl font-medium text-white mt-6 mb-3">Types of Data Collected</h3>
            
            <h4 className="text-lg font-medium text-white mt-4 mb-2">Personal Data</h4>
            <p className="text-zinc-300 leading-relaxed mb-4">
              While using Our Service, We may ask You to provide Us with certain personally identifiable 
              information that can be used to contact or identify You. Personally identifiable information 
              may include, but is not limited to:
            </p>
            <ul className="list-disc list-inside text-zinc-300 space-y-2">
              <li>Email address</li>
              <li>First name and last name</li>
              <li>LinkedIn conversation data (uploaded by you)</li>
            </ul>

            <p className="text-zinc-300 leading-relaxed mt-4">
              When you visit or log into our website, we use cookies and similar technologies to collect 
              certain information about your visit. This includes (i) Usage Data (Information about how you 
              use our site, such as pages visited, time spent on pages, and links clicked.) (ii) Device 
              Information (Details about the device you use to access our site, including IP address, browser 
              type, and operating system.) and (iii) Personal Data (If you provide it, we may collect 
              information such as your email address or other contact details).
            </p>

            <h4 className="text-lg font-medium text-white mt-6 mb-2">Usage Data</h4>
            <p className="text-zinc-300 leading-relaxed">
              Usage Data is collected automatically when using the Service. Usage Data may include information 
              such as Your Device's Internet Protocol address (e.g. IP address), browser type, browser version, 
              the pages of our Service that You visit, the time and date of Your visit, the time spent on those 
              pages, unique device identifiers and other diagnostic data.
            </p>
            <p className="text-zinc-300 leading-relaxed mt-4">
              When You access the Service by or through a mobile device, We may collect certain information 
              automatically, including, but not limited to, the type of mobile device You use, Your mobile 
              device unique ID, the IP address of Your mobile device, Your mobile operating system, the type 
              of mobile Internet browser You use, unique device identifiers and other diagnostic data.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Tracking Technologies and Cookies</h2>
            <p className="text-zinc-300 leading-relaxed mb-4">
              We use Cookies and similar tracking technologies to track the activity on Our Service and store 
              certain information. Tracking technologies used are beacons, tags, and scripts to collect and 
              track information and to improve and analyze Our Service.
            </p>
            
            <h3 className="text-xl font-medium text-white mt-6 mb-3">Types of Cookies We Use</h3>
            
            <h4 className="text-lg font-medium text-white mt-4 mb-2">Necessary / Essential Cookies</h4>
            <p className="text-zinc-300 leading-relaxed">
              <strong>Type:</strong> Session Cookies<br />
              <strong>Administered by:</strong> Us<br />
              <strong>Purpose:</strong> These Cookies are essential to provide You with services available 
              through the Website and to enable You to use some of its features. They help to authenticate 
              users and prevent fraudulent use of user accounts.
            </p>

            <h4 className="text-lg font-medium text-white mt-4 mb-2">Cookies Policy / Notice Acceptance Cookies</h4>
            <p className="text-zinc-300 leading-relaxed">
              <strong>Type:</strong> Persistent Cookies<br />
              <strong>Administered by:</strong> Us<br />
              <strong>Purpose:</strong> These Cookies identify if users have accepted the use of cookies on the Website.
            </p>

            <h4 className="text-lg font-medium text-white mt-4 mb-2">Functionality Cookies</h4>
            <p className="text-zinc-300 leading-relaxed">
              <strong>Type:</strong> Persistent Cookies<br />
              <strong>Administered by:</strong> Us<br />
              <strong>Purpose:</strong> These Cookies allow us to remember choices You make when You use the 
              Website, such as remembering your login details or language preference.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Use of Your Personal Data</h2>
            <p className="text-zinc-300 mb-2">The Company may use Personal Data for the following purposes:</p>
            <ul className="list-disc list-inside text-zinc-300 space-y-2">
              <li><strong>To provide and maintain our Service</strong>, including to monitor the usage of our Service.</li>
              <li><strong>To manage Your Account</strong>: to manage Your registration as a user of the Service.</li>
              <li><strong>For the performance of a contract</strong>: the development, compliance and undertaking of the purchase contract for the services You have purchased.</li>
              <li><strong>To contact You</strong>: To contact You by email regarding updates or informative communications related to the Service.</li>
              <li><strong>To provide You</strong> with news, special offers and general information about other services which we offer.</li>
              <li><strong>To manage Your requests</strong>: To attend and manage Your requests to Us.</li>
              <li><strong>For business transfers</strong>: We may use Your information to evaluate or conduct a merger, divestiture, restructuring, or other sale or transfer of assets.</li>
              <li><strong>For other purposes</strong>: such as data analysis, identifying usage trends, and improving our Service.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Sharing Your Personal Information</h2>
            <p className="text-zinc-300 mb-2">We may share Your personal information in the following situations:</p>
            <ul className="list-disc list-inside text-zinc-300 space-y-2">
              <li><strong>With Service Providers</strong>: We may share Your personal information with Service Providers to monitor and analyze the use of our Service.</li>
              <li><strong>For business transfers</strong>: We may share or transfer Your personal information in connection with any merger, sale of Company assets, financing, or acquisition.</li>
              <li><strong>With Affiliates</strong>: We may share Your information with Our affiliates, in which case we will require those affiliates to honor this Privacy Policy.</li>
              <li><strong>With Your consent</strong>: We may disclose Your personal information for any other purpose with Your consent.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Retention of Your Personal Data</h2>
            <p className="text-zinc-300 leading-relaxed">
              The Company will retain Your Personal Data only for as long as is necessary for the purposes set 
              out in this Privacy Policy. We will retain and use Your Personal Data to the extent necessary to 
              comply with our legal obligations, resolve disputes, and enforce our legal agreements and policies.
            </p>
            <p className="text-zinc-300 leading-relaxed mt-4">
              The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally 
              retained for a shorter period of time, except when this data is used to strengthen the security 
              or to improve the functionality of Our Service.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Transfer of Your Personal Data</h2>
            <p className="text-zinc-300 leading-relaxed">
              Your information, including Personal Data, is processed at the Company's operating offices and 
              in any other places where the parties involved in the processing are located. It means that this 
              information may be transferred to — and maintained on — computers located outside of Your state, 
              province, country or other governmental jurisdiction where the data protection laws may differ 
              than those from Your jurisdiction.
            </p>
            <p className="text-zinc-300 leading-relaxed mt-4">
              Your consent to this Privacy Policy followed by Your submission of such information represents 
              Your agreement to that transfer. The Company will take all steps reasonably necessary to ensure 
              that Your data is treated securely and in accordance with this Privacy Policy.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Delete Your Personal Data</h2>
            <p className="text-zinc-300 leading-relaxed">
              You have the right to delete or request that We assist in deleting the Personal Data that We 
              have collected about You. Our Service may give You the ability to delete certain information 
              about You from within the Service.
            </p>
            <p className="text-zinc-300 leading-relaxed mt-4">
              You may update, amend, or delete Your information at any time by signing in to Your Account, 
              if you have one, and visiting the account settings section that allows you to manage Your 
              personal information. You may also contact Us to request access to, correct, or delete any 
              personal information that You have provided to Us.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Disclosure of Your Personal Data</h2>
            
            <h3 className="text-xl font-medium text-white mt-6 mb-3">Business Transactions</h3>
            <p className="text-zinc-300 leading-relaxed">
              If the Company is involved in a merger, acquisition or asset sale, Your Personal Data may be 
              transferred. We will provide notice before Your Personal Data is transferred and becomes subject 
              to a different Privacy Policy.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">Law Enforcement</h3>
            <p className="text-zinc-300 leading-relaxed">
              Under certain circumstances, the Company may be required to disclose Your Personal Data if 
              required to do so by law or in response to valid requests by public authorities.
            </p>

            <h3 className="text-xl font-medium text-white mt-6 mb-3">Other Legal Requirements</h3>
            <p className="text-zinc-300 mb-2">
              The Company may disclose Your Personal Data in the good faith belief that such action is necessary to:
            </p>
            <ul className="list-disc list-inside text-zinc-300 space-y-2">
              <li>Comply with a legal obligation</li>
              <li>Protect and defend the rights or property of the Company</li>
              <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
              <li>Protect the personal safety of Users of the Service or the public</li>
              <li>Protect against legal liability</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Security of Your Personal Data</h2>
            <p className="text-zinc-300 leading-relaxed">
              The security of Your Personal Data is important to Us, but remember that no method of 
              transmission over the Internet, or method of electronic storage is 100% secure. While We 
              strive to use commercially acceptable means to protect Your Personal Data, We cannot guarantee 
              its absolute security.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Children's Privacy</h2>
            <p className="text-zinc-300 leading-relaxed">
              Our Service does not address anyone under the age of 13. We do not knowingly collect personally 
              identifiable information from anyone under the age of 13. If You are a parent or guardian and 
              You are aware that Your child has provided Us with Personal Data, please contact Us.
            </p>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">LinkedIn Data Handling</h2>
            <p className="text-zinc-300 leading-relaxed mb-4">
              LinkedInbox allows users to upload their LinkedIn messages export for analysis. Here's how we 
              handle this data:
            </p>
            <ul className="list-disc list-inside text-zinc-300 space-y-2">
              <li><strong>Data Upload:</strong> You upload your LinkedIn messages CSV file directly to our service.</li>
              <li><strong>Data Processing:</strong> We process your conversation data to provide analytics and insights about your outreach performance.</li>
              <li><strong>Data Storage:</strong> Your conversation data is stored securely and associated with your account.</li>
              <li><strong>AI Analysis:</strong> We use AI to analyze conversation patterns, but we do not share your conversation content with third parties.</li>
              <li><strong>Data Deletion:</strong> You can request deletion of your data at any time by contacting us.</li>
            </ul>
          </section>

          <section className="mb-12">
            <h2 className="text-2xl font-semibold text-white mb-4">Contact Us</h2>
            <p className="text-zinc-300 leading-relaxed">
              If you have any questions about this Privacy Policy, You can contact us:
            </p>
            <p className="text-zinc-300 mt-4">
              <strong>By email:</strong> hello@linkedinbox.co
            </p>
          </section>
        </div>
      </div>
    </div>
  );
}
